BEGIN;

-- TABLES

INSERT INTO road_graph.managed_objects (
    schema_name, table_name, object_type, geometry_type,
    update_geom_on_graph_change, update_references_on_graph_change
)
VALUES
('road_graph', 'demo_trees', 'tree', 'POINT', false, true),
('road_graph', 'demo_safety_barriers', 'safety_barrier', 'MULTILINESTRING', false, true)
;



DROP TABLE IF EXISTS road_graph.demo_trees;
CREATE TABLE road_graph.demo_trees (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    species text NOT NULL,
    road_code text,
    marker_code integer,
    abscissa real,
    side text,
    "offset" real,
    geom geometry(POINT, 2154)
);
COMMENT ON TABLE road_graph.demo_trees IS 'Demo table for trees managed objects in the road graph system';
CREATE INDEX ON road_graph.demo_trees USING GIST (geom);
COMMENT ON COLUMN road_graph.demo_trees.road_code IS 'Road code reference';
COMMENT ON COLUMN road_graph.demo_trees.marker_code IS 'Marker code reference';
COMMENT ON COLUMN road_graph.demo_trees.abscissa IS 'Abscissa reference';
COMMENT ON COLUMN road_graph.demo_trees.side IS 'Side reference (left or right)';
COMMENT ON COLUMN road_graph.demo_trees.offset IS 'Offset reference (in meters)';

INSERT INTO road_graph.demo_trees (species, road_code, marker_code, abscissa, side, "offset")
VALUES
('Oak', 'D100', 1, 150.0, 'left', 5.0),
('Pine', 'D101', 2, 300.0, 'right', 3.0),
('Maple', 'D102', 1, 100.0, 'left', 4.0);

WITH updated_trees AS (
    SELECT
        t.id,
        t.species,
        t.road_code,
        t.marker_code,
        t.abscissa,
        t.side,
        t."offset",
        -- Get geometry from references
        (road_graph.get_road_point_from_reference(
            t.road_code,
            t.marker_code,
            t.abscissa,
            t."offset",
            t.side
        )->>'geom')::geometry(POINT, 2154) AS geom
    FROM
        road_graph.demo_trees AS t
)
UPDATE road_graph.demo_trees AS t
SET geom = u.geom
FROM updated_trees AS u
WHERE t.id = u.id
;

-- demo safety barriers table
DROP TABLE IF EXISTS road_graph.demo_safety_barriers;
CREATE TABLE road_graph.demo_safety_barriers (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material text NOT NULL,
    start_road_code text,
    start_marker_code integer,
    start_abscissa real,
    end_road_code text,
    end_marker_code integer,
    end_abscissa real,
    "offset" real,
    side text,
    geom geometry(MULTILINESTRING, 2154)
);
COMMENT ON TABLE road_graph.demo_safety_barriers IS 'Demo table for safety barriers managed objects in the road graph system';
CREATE INDEX ON road_graph.demo_safety_barriers USING GIST (geom);
COMMENT ON COLUMN road_graph.demo_safety_barriers.start_road_code IS 'Start road code reference';
COMMENT ON COLUMN road_graph.demo_safety_barriers.start_marker_code IS 'Start marker code reference';
COMMENT ON COLUMN road_graph.demo_safety_barriers.start_abscissa IS 'Start abscissa reference';
COMMENT ON COLUMN road_graph.demo_safety_barriers.end_road_code IS 'End road code reference';
COMMENT ON COLUMN road_graph.demo_safety_barriers.end_marker_code IS 'End marker code reference';
COMMENT ON COLUMN road_graph.demo_safety_barriers.end_abscissa IS 'End abscissa reference';
COMMENT ON COLUMN road_graph.demo_safety_barriers.side IS 'Side reference (left or right)';
COMMENT ON COLUMN road_graph.demo_safety_barriers.offset IS 'Offset reference (in meters)';
INSERT INTO road_graph.demo_safety_barriers (material, road_code, start_marker_code, start_abscissa, end_marker_code, end_abscissa, side, "offset")
VALUES
('Metal', 'D100', 1, 120.0, 2, 180.0, 'right', 2.0),
('Concrete', 'D101', 2, 250.0, 5, 350.0, 'right', 1.5),
('Wood', 'D102', 1, 80.0, 6, 150.0, 'right', 3.0);

WITH updated_barriers AS (
    SELECT
        b.id,
        b.material,
        b.road_code,
        b.start_marker_code,
        b.start_abscissa,
        b.end_marker_code,
        b.end_abscissa,
        b.side,
        b."offset",
        -- Get geometry from references
        (road_graph.get_road_substring_from_references(
            b.road_code,
            b.start_marker_code,
            b.start_abscissa,
            b.end_marker_code,
            b.end_abscissa,
            b."offset",
            b.side
        )->>'geom')::geometry(MULTILINESTRING, 2154) AS geom
    FROM
        road_graph.demo_safety_barriers AS b
)
UPDATE road_graph.demo_safety_barriers AS b
SET geom = u.geom
FROM updated_barriers AS u
WHERE b.id = u.id
;

COMMIT;
