--
-- PostgreSQL database dump
--






SET statement_timeout = 0;
SET lock_timeout = 0;


SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

;

-- edges
CREATE TABLE road_graph.edges (
    id integer NOT NULL,
    road_code text NOT NULL,
    start_node integer,
    end_node integer,
    start_marker integer,
    start_abscissa real,
    start_cumulative real,
    end_marker integer,
    end_abscissa real,
    end_cumulative real,
    created_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    updated_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    geom geometry(LineString,2154) NOT NULL,
    previous_edge_id integer,
    next_edge_id integer,
    uid text DEFAULT (public.uuid_generate_v4())::text
);


-- edges
COMMENT ON TABLE road_graph.edges IS 'Road graph edges';


-- edges_id_seq
ALTER TABLE road_graph.edges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME road_graph.edges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- editing_sessions
CREATE TABLE road_graph.editing_sessions (
    id integer NOT NULL,
    label text NOT NULL,
    author text NOT NULL,
    created_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    updated_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    description text,
    geom geometry(Polygon,2154),
    status text DEFAULT 'created'::text NOT NULL,
    unique_code text DEFAULT concat('editing_session_', to_char(now(), 'YYYY_MM_DD_HH_MI_SS'::text)) NOT NULL,
    cloned_ids jsonb,
    logged_ids jsonb
);


-- editing_sessions_id_seq
ALTER TABLE road_graph.editing_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME road_graph.editing_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- glossary_road_class
CREATE TABLE road_graph.glossary_road_class (
    id integer NOT NULL,
    code text NOT NULL,
    label text NOT NULL
);


-- glossary_road_class
COMMENT ON TABLE road_graph.glossary_road_class IS 'Glossary for the column road_scale of the table roads';


-- glossary_road_scale_id_seq
ALTER TABLE road_graph.glossary_road_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME road_graph.glossary_road_scale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- markers
CREATE TABLE road_graph.markers (
    id integer NOT NULL,
    road_code text NOT NULL,
    code integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    updated_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    geom geometry(Point,2154) NOT NULL,
    abscissa real DEFAULT 0,
    is_virtual boolean DEFAULT false,
    uid text DEFAULT (public.uuid_generate_v4())::text
);


-- markers
COMMENT ON TABLE road_graph.markers IS 'Road distance markers';


-- markers_id_seq
ALTER TABLE road_graph.markers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME road_graph.markers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- metadata
CREATE TABLE road_graph.metadata (
    id integer NOT NULL,
    me_version text NOT NULL,
    me_version_date date NOT NULL,
    me_status smallint NOT NULL
);


-- metadata
COMMENT ON TABLE road_graph.metadata IS 'Metadata of the structure : version and date. Usefull for database structure and glossary data migrations between versions';


-- nodes
CREATE TABLE road_graph.nodes (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    updated_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    geom geometry(Point,2154) NOT NULL,
    uid text DEFAULT (public.uuid_generate_v4())::text
);


-- nodes
COMMENT ON TABLE road_graph.nodes IS 'Road graph nodes';


-- nodes_id_seq
ALTER TABLE road_graph.nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME road_graph.nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- roads
CREATE TABLE road_graph.roads (
    id integer NOT NULL,
    road_code text NOT NULL,
    road_type text DEFAULT 'road'::text NOT NULL,
    road_class text NOT NULL,
    road_class_code text,
    is_active boolean DEFAULT true,
    road_topic text,
    is_access_road boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    updated_at timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    uid text DEFAULT (public.uuid_generate_v4())::text,
    CONSTRAINT roads_road_type_values CHECK ((road_type = ANY (ARRAY['road'::text, 'roundabout'::text])))
);


-- roads
COMMENT ON TABLE road_graph.roads IS 'Roads. This is a non-spatial table listing all unique roads codes. It is a parent of the table edges.';


-- roads_id_seq
ALTER TABLE road_graph.roads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME road_graph.roads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- PostgreSQL database dump complete
--



