--
-- PostgreSQL database dump
--






SET statement_timeout = 0;
SET lock_timeout = 0;


SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

;

-- glossary_test_category
CREATE TABLE road_graph.glossary_test_category (
    id integer NOT NULL,
    code text NOT NULL,
    label text NOT NULL
);


-- glossary_test_category
COMMENT ON TABLE road_graph.glossary_test_category IS 'Glossary for the column category of the table test';


-- glossary_test_category_id_seq
ALTER TABLE road_graph.glossary_test_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME road_graph.glossary_test_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- metadata
CREATE TABLE road_graph.metadata (
    id integer NOT NULL,
    me_version text NOT NULL,
    me_version_date date NOT NULL,
    me_status smallint NOT NULL
);


-- metadata
COMMENT ON TABLE road_graph.metadata IS 'Metadata of the structure : version and date. Useful for database structure and glossary data migrations between versions';


-- test
CREATE TABLE road_graph.test (
    id integer NOT NULL,
    label text,
    category text
);


-- test
COMMENT ON TABLE road_graph.test IS 'Test table';


-- test_id_seq
CREATE SEQUENCE road_graph.test_id_seq

    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


-- test_id_seq
ALTER SEQUENCE road_graph.test_id_seq OWNED BY road_graph.test.id;


-- test id
ALTER TABLE ONLY road_graph.test ALTER COLUMN id SET DEFAULT nextval('road_graph.test_id_seq'::regclass);


--
-- PostgreSQL database dump complete
--



